default: &defaults
  host: <%= Rails.application.secrets['redis']['host'] %>
  port: <%= Rails.application.secrets['redis']['port'] %>

development:
  <<: *defaults
test:
  <<: *defaults
production:
  <<: *defaults
